// HookGenerator.swift
// Generates the "point an app at a route's listener" artifacts (P1, VPN-Bypass-3sc.8):
//  - shell exports (HTTPS_PROXY=…) for the `route-on` hook (iTerm / shells)
//  - a PAC script that sends matching hosts through the listener, else DIRECT (browsers)
// Pure string generation, no side effects — unit-testable. The listener itself
// is ProxyForwarder; this only tells clients how to reach it.

import Foundation

enum HookGenerator {

    /// Shell export block pointing HTTP(S)_PROXY at a route's local listener.
    /// Sourcing it routes that shell's HTTP(S) traffic through the route; the
    /// no_proxy entries keep loopback (incl. the listener itself) direct.
    static func shellExports(port: UInt16) -> String {
        let url = "http://127.0.0.1:\(port)"
        return """
        export HTTP_PROXY="\(url)"
        export HTTPS_PROXY="\(url)"
        export http_proxy="\(url)"
        export https_proxy="\(url)"
        export NO_PROXY="localhost,127.0.0.1,::1"
        export no_proxy="localhost,127.0.0.1,::1"
        """
    }

    /// A PAC (proxy auto-config) script: a host that equals one of `domainPatterns`
    /// or is a sub-domain of it goes through the route's listener; everything else
    /// is DIRECT. The dot-boundary match mirrors the resolver's `suffix` rule.
    /// Patterns are JSON-encoded, so they cannot break out of the generated script.
    static func pac(port: UInt16, domainPatterns: [String]) -> String {
        let proxy = "PROXY 127.0.0.1:\(port)"
        let normalized = domainPatterns.map { $0.lowercased() }
        let patternsJSON = (try? JSONEncoder().encode(normalized)).flatMap { String(data: $0, encoding: .utf8) } ?? "[]"
        return """
        // Generated by VPN Bypass — route specific hosts through a local proxy listener.
        function FindProxyForURL(url, host) {
            host = host.toLowerCase();
            var patterns = \(patternsJSON);
            for (var i = 0; i < patterns.length; i++) {
                var p = patterns[i];
                if (host === p || dnsDomainIs(host, "." + p)) {
                    return "\(proxy)";
                }
            }
            return "DIRECT";
        }
        """
    }
}
